name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: npm

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Vite Assets
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Upload Built Assets via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 65002
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          source: "public/build/*"
          target: "/home/u344492505/domains/tkaisyiyah-mimika.sch.id/laravel/public/build/"

      - name: Upload Vendor via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 65002
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          source: "vendor/*"
          target: "/home/u344492505/domains/tkaisyiyah-mimika.sch.id/laravel/vendor/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: 145.223.108.173
          port: 65002
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /home/u344492505/domains/tkaisyiyah-mimika.sch.id/laravel
            git stash
            git pull origin main
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link